name: AbeoVanish
version: '1.0-SNAPSHOT'
main: eu.mikart.abeovanish.AbeoBukkit
api-version: '1.21'
authors: [ ArikSquad ]
description: Modular vanish-system
folia-supported: true
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  abeovanish.vanish:
    default: op
    description: Allows the player to use the vanish command
  abeovanish.see:
    default: op
    description: Allows the player to see vanished players
  abeovanish.reload:
    default: op
    description: Allows the player to reload the plugin
  abeovanish.about:
    default: true
    description: Allows the player to see the plugin information
